name: Publish Docs
on:
  workflow_dispatch:
    inputs:
      tag:
        description: Docker Image Tag
        required: true
        default: latest

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - uses: docker/login-action@v3
        with:
          registry: https://${{ secrets.DOCKER_REGISTRY_HOSTNAME }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - run: pnpm docs:build
      - run: docker build docs/.vitepress -t ${{ secrets.DOCKER_REGISTRY_HOSTNAME }}/wxt/docs:${{ github.event.inputs.tag }}
      - run: docker push ${{ secrets.DOCKER_REGISTRY_HOSTNAME }}/wxt/docs:${{ github.event.inputs.tag }}
      - run: curl -X POST ${{ secrets.UPDATE_DOCS_WEBHOOK }}
