name: Release
on:
  workflow_dispatch:

jobs:
  validate:
    uses: './.github/workflows/validate.yml'
    secrets: inherit

  publish:
    runs-on: ubuntu-22.04
    needs:
      - validate
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup

      - name: Bump and Tag
        run: |
          git config user.email "github-actions@users.noreply.github.com"
          git config user.name "GitHub Actions"
          pnpx changelogen@latest --release
          git push
          git push --tags

      - name: NPM
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc
          pnpm publish

      - name: GitHub Release
        run: pnpx changelogen@latest gh release --token ${{ secrets.GITHUB_TOKEN }}
