name: Release
on:
  workflow_dispatch:
    inputs:
      package:
        description: Package to release
        default: wxt
        type: choice
        options:
          - wxt

jobs:
  validate:
    uses: './.github/workflows/validate.yml'
    secrets: inherit

  publish:
    runs-on: ubuntu-22.04
    needs:
      - validate
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup

      - name: Bump and Tag
        run: |
          git config user.email "github-actions@users.noreply.github.com"
          git config user.name "GitHub Actions"
          pnpm tsx scripts/bump-package-version.ts ${{ inputs.package }}
          git push
          git push --tags

      - name: NPM
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc
          pnpm build
          pnpm publish
        working-directory: packages/${{ inputs.package }}

      - name: GitHub Release
        run: pnpm tsx scripts/create-github-release.ts ${{ inputs.package }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
